# Proyecto de análisis y manipulación de datos con NumPy

Este proyecto tiene como objetivo demostrar el uso de NumPy en la creación, manipulación y análisis de datos.

### Parte 1: Creación y manipulación de arrays (30 puntos)

#### Creación de un array de 10 elementos enteros aleatorios entre 1 y 100


In [5]:
import numpy as np

# Crear un array de 10 elementos aleatorios entre 1 y 100
array = np.random.randint(1, 101, size=10)
print("Array original:")
print(array)


Array original:
[48 44  4 82 69 86 65 57 82 58]


### Convertir el array en una matriz 2x5

In [6]:
matriz = array.reshape(2, 5)
print("\nMatriz 2x5:")
print(matriz)


Matriz 2x5:
[[48 44  4 82 69]
 [86 65 57 82 58]]


### Extraer la primera fila

In [7]:
primera_fila = matriz[0, :]
print("\nPrimera fila:")
print(primera_fila)


Primera fila:
[48 44  4 82 69]


### Extraer la última columna

In [8]:
ultima_columna = matriz[:, -1]
print("\nÚltima columna:")
print(ultima_columna)


Última columna:
[69 58]


### Cambiar la segunda fila a ceros

In [9]:
matriz[1, :] = 0
print("\nMatriz después de cambiar la segunda fila a ceros:")
print(matriz)


Matriz después de cambiar la segunda fila a ceros:
[[48 44  4 82 69]
 [ 0  0  0  0  0]]


## Parte 2: Operaciones básicas con NumPy (30 puntos)
#### Operaciones aritméticas: Suma y multiplicación de dos arrays de 5 element

### Crear dos arrays de 5 elementos aleatorios entre 1 y 50

In [10]:
array1 = np.random.randint(1, 51, size=5)
array2 = np.random.randint(1, 51, size=5)
print("\nArray 1:")
print(array1)
print("\nArray 2:")
print(array2)


Array 1:
[30 33 15 43  3]

Array 2:
[41  2  3 42 13]


### Suma de ambos arrays

In [11]:
suma_arrays = array1 + array2
print("\nSuma de los arrays:")
print(suma_arrays)


Suma de los arrays:
[71 35 18 85 16]


### Multiplicación de ambos arrays

In [12]:
multiplicacion_arrays = array1 * array2
print("\nMultiplicación de los arrays:")
print(multiplicacion_arrays)


Multiplicación de los arrays:
[1230   66   45 1806   39]


### Cálculo del promedio y la desviación estándar

In [13]:
promedio = np.mean(multiplicacion_arrays)
desviacion_estandar = np.std(multiplicacion_arrays)
print("\nPromedio de la multiplicación de los arrays:")
print(promedio)
print("\nDesviación estándar de la multiplicación de los arrays:")
print(desviacion_estandar)


Promedio de la multiplicación de los arrays:
637.2

Desviación estándar de la multiplicación de los arrays:
741.9324497553669


#### Condiciones lógicas: Reemplazo de valores en un array de números aleatorios entre 0 y 1
### Crear un array de 20 números aleatorios entre 0 y 1

In [14]:
array_aleatorio = np.random.rand(20)
print("\nArray aleatorio entre 0 y 1:")
print(array_aleatorio)


Array aleatorio entre 0 y 1:
[0.05686081 0.27991528 0.54936219 0.85183785 0.05378412 0.06730326
 0.21976034 0.60530923 0.27666761 0.37872229 0.82871841 0.71678764
 0.12535257 0.31732047 0.98676658 0.69611774 0.48246708 0.42448823
 0.72373197 0.82319719]


### Reemplazar los valores menores a 0.5 con 0

In [15]:
array_aleatorio[array_aleatorio < 0.5] = 0

### Reemplazar los valores mayores o iguales a 0.5 con 1

In [16]:
array_aleatorio[array_aleatorio >= 0.5] = 1
print("\nArray después de aplicar condiciones lógicas:")
print(array_aleatorio)


Array después de aplicar condiciones lógicas:
[0. 0. 1. 1. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0. 1. 1. 0. 0. 1. 1.]


#### Producto escalar de dos matrices 3x3

### Crear dos arrays 3x3

In [17]:
matriz1 = np.random.randint(1, 10, size=(3, 3))
matriz2 = np.random.randint(1, 10, size=(3, 3))
print("\nMatriz 1:")
print(matriz1)
print("\nMatriz 2:")
print(matriz2)


Matriz 1:
[[5 8 6]
 [7 7 1]
 [4 3 7]]

Matriz 2:
[[6 9 3]
 [8 2 5]
 [2 3 9]]


### Producto escalar

In [18]:
producto_escalar = np.dot(matriz1, matriz2)
print("\nProducto escalar de las matrices:")
print(producto_escalar)


Producto escalar de las matrices:
[[106  79 109]
 [100  80  65]
 [ 62  63  90]]


## Parte 3: Análisis de datos con NumPy (40 puntos)

#### Creación de una matriz de datos de 5 filas y 4 columnas con datos aleatorios entre 1 y 20

### Crear una matriz de 5 filas y 4 columnas con datos aleatorios entre 1 y 20

In [19]:
datos = np.random.randint(1, 21, size=(5, 4))
print("\nMatriz de datos (cada fila representa una persona, cada columna una medición):")
print(datos)


Matriz de datos (cada fila representa una persona, cada columna una medición):
[[ 5 17 19  8]
 [17 11  9  7]
 [11  9 20 20]
 [12 13  1  9]
 [ 2 20  2  5]]


### Estadísticas
#### 1. Calcular la media de cada columna (medición)
### Media de cada columna

In [20]:
media_columnas = np.mean(datos, axis=0)
print("\nMedia de cada columna:")
print(media_columnas)


Media de cada columna:
[ 9.4 14.  10.2  9.8]


#### 2. Encontrar el valor máximo y mínimo de cada fila

### Máximo y mínimo de cada fila

In [21]:
max_filas = np.max(datos, axis=1)
min_filas = np.min(datos, axis=1)
print("\nMáximo de cada fila:")
print(max_filas)
print("\nMínimo de cada fila:")
print(min_filas)


Máximo de cada fila:
[19 17 20 13 20]

Mínimo de cada fila:
[5 7 9 1 2]


#### 3. Ordenar las filas según los valores de la segunda columna (peso)

### Ordenar las filas según la segunda columna (índice 1) 

In [22]:
datos_ordenados = datos[datos[:, 1].argsort()]
print("\nMatriz ordenada según la segunda columna (peso):")
print(datos_ordenados)


Matriz ordenada según la segunda columna (peso):
[[11  9 20 20]
 [17 11  9  7]
 [12 13  1  9]
 [ 5 17 19  8]
 [ 2 20  2  5]]
